CREATE TABLE USUARIOS (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    SOBRENOME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    DATA_NASCIMENTO DATETIME NOT NULL,
    ESCOLARIDADE INT NOT NULL
);